### ISSUE TITLE
Installation should work on Clinical-db

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/genotype#36]
```
(prod170926) [hiseq.clinical@hippocampus clinical-db.scilifelab.se]$ bash ~/STAGE/servers/resources/clinical-db.scilifelab.se/update-genotype-stage.sh master
running script as user hiseq.clinical, continue
on the host clinical-db.scilifelab.se, continue
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/Clinical-Genomics/genotype
 * branch            master     -> FETCH_HEAD
   3d666e2..3882cda  master     -> origin/master
Updating 905a465..3882cda
Fast-forward
 .bumpversion.cfg | 2 +-
 setup.py         | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
Processing /home/hiseq.clinical/STAGE/genotype
Requirement already satisfied, skipping upgrade: click in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (6.7)
Requirement already satisfied, skipping upgrade: PyYAML in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (5.3)
Requirement already satisfied, skipping upgrade: Alchy in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (2.2.2)
Requirement already satisfied, skipping upgrade: SQLAlchemy in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (1.3.13)
Requirement already satisfied, skipping upgrade: cyvcf2<0.10.0 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.9.0)
Requirement already satisfied, skipping upgrade: xlrd in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (1.2.0)
Requirement already satisfied, skipping upgrade: pymysql in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.9.3)
Requirement already satisfied, skipping upgrade: pysam in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.15.2)
Requirement already satisfied, skipping upgrade: Flask in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (1.1.1)
Requirement already satisfied, skipping upgrade: Flask-Bootstrap in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (3.3.7.1)
Requirement already satisfied, skipping upgrade: Flask-Reverse-Proxy in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.2.0.2)
Requirement already satisfied, skipping upgrade: Flask-SQLAlchemy==2.1 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (2.1)
Requirement already satisfied, skipping upgrade: Flask-Alchy in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.5.0)
Requirement already satisfied, skipping upgrade: Flask-Security in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (3.0.0)
Requirement already satisfied, skipping upgrade: werkzeug<1.0.0 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.16.1)
Requirement already satisfied, skipping upgrade: Flask-Login in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.4.1)
Requirement already satisfied, skipping upgrade: Flask-Dance in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (3.0.0)
Requirement already satisfied, skipping upgrade: ruamel.yaml in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (0.16.7)
Requirement already satisfied, skipping upgrade: six~=1.12 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from genotype==2.3.3) (1.12.0)
Requirement already satisfied, skipping upgrade: pydash>=3.4.7 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Alchy->genotype==2.3.3) (4.7.6)
Requirement already satisfied, skipping upgrade: numpy in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from cyvcf2<0.10.0->genotype==2.3.3) (1.18.1)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask->genotype==2.3.3) (1.1.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10.1 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask->genotype==2.3.3) (2.11.1)
Requirement already satisfied, skipping upgrade: visitor in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Bootstrap->genotype==2.3.3) (0.1.3)
Requirement already satisfied, skipping upgrade: dominate in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Bootstrap->genotype==2.3.3) (2.4.0)
Requirement already satisfied, skipping upgrade: Flask-Mail>=0.7.3 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Security->genotype==2.3.3) (0.9.1)
Requirement already satisfied, skipping upgrade: Flask-Principal>=0.3.3 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Security->genotype==2.3.3) (0.4.0)
Requirement already satisfied, skipping upgrade: Flask-WTF>=0.13.1 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Security->genotype==2.3.3) (0.14.2)
Requirement already satisfied, skipping upgrade: passlib>=1.7 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Security->genotype==2.3.3) (1.7.2)
Requirement already satisfied, skipping upgrade: Flask-BabelEx>=0.9.3 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Security->genotype==2.3.3) (0.9.3)
Requirement already satisfied, skipping upgrade: oauthlib in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Dance->genotype==2.3.3) (2.1.0)
Requirement already satisfied, skipping upgrade: requests>=2.0 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Dance->genotype==2.3.3) (2.22.0)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=1.0.0 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Dance->genotype==2.3.3) (1.1.0)
Requirement already satisfied, skipping upgrade: urlobject in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Dance->genotype==2.3.3) (2.4.3)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from ruamel.yaml->genotype==2.3.3) (0.2.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Jinja2>=2.10.1->Flask->genotype==2.3.3) (1.1.1)
Requirement already satisfied, skipping upgrade: blinker in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-Mail>=0.7.3->Flask-Security->genotype==2.3.3) (1.4)
Requirement already satisfied, skipping upgrade: WTForms in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-WTF>=0.13.1->Flask-Security->genotype==2.3.3) (2.2.1)
Requirement already satisfied, skipping upgrade: Babel>=1.0 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-BabelEx>=0.9.3->Flask-Security->genotype==2.3.3) (2.8.0)
Requirement already satisfied, skipping upgrade: speaklater>=1.2 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Flask-BabelEx>=0.9.3->Flask-Security->genotype==2.3.3) (1.3)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from requests>=2.0->Flask-Dance->genotype==2.3.3) (2019.11.28)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from requests>=2.0->Flask-Dance->genotype==2.3.3) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from requests>=2.0->Flask-Dance->genotype==2.3.3) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from requests>=2.0->Flask-Dance->genotype==2.3.3) (1.25.8)
Requirement already satisfied, skipping upgrade: pytz>=2015.7 in /home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages (from Babel>=1.0->Flask-BabelEx>=0.9.3->Flask-Security->genotype==2.3.3) (2019.3)
Building wheels for collected packages: genotype
  Building wheel for genotype (setup.py) ... done
  Created wheel for genotype: filename=genotype-2.3.3-py2.py3-none-any.whl size=29596 sha256=b48e680919a4931ec877b178b4909f08e41eaa51daf80cb17efbecff56ff6f9e
  Stored in directory: /tmp/pip-ephem-wheel-cache-sf_rys0g/wheels/28/e2/37/f3eabc7a923a7c5db87e6e444d2d9d4e916fca93c7550a18d3
Successfully built genotype
Installing collected packages: genotype
  Found existing installation: genotype 2.3.2
    Uninstalling genotype-2.3.2:
      Successfully uninstalled genotype-2.3.2
Successfully installed genotype-2.3.3
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
genotype-stage: stopped
genotype-stage: started
/home/hiseq.clinical/servers/resources/clinical-db.scilifelab.se
repository is dirty
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../../config/clinical-db.scilifelab.se/scout-stage.conf.py.old
	src/

nothing added to commit but untracked files present (use "git add" to track)
This deletes any changed/untracked files, are you sure? y/[n]y
HEAD is now at f3077c2 Bump version: 3.3.2 → 4.0.0
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/hiseq.clinical/servers/resources/clinical-db.scilifelab.se
done.
Log deploy... done.
Running --version on each Clinical-Genomics developed tool to verify that all requirements are met:
networkx 2.3 has requirement decorator>=4.3.0, but you have decorator 4.1.2.
/home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py:2059: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
cg, version 7.11.0
genotype, version 2.3.3
housekeeper, version 2.5.0
trailblazer, version 6.1.0
/home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages/weasyprint/text.py:28: UserWarning: There are known rendering problems with Cairo <= 1.14.0
  warnings.warn('There are known rendering problems with Cairo <= 1.14.0')
/home/hiseq.clinical/miniconda/envs/stage/lib/python3.6/site-packages/weasyprint/fonts.py:43: UserWarning: @font-face support needs Pango >= 1.38
  warnings.warn('@font-face support needs Pango >= 1.38')
scout, version 4.11.1
(prod170926) [hiseq.clinical@hippocampus clinical-db.scilifelab.se]$ bash ~/STAGE/servers/resources/clinical-db.scilifelab.se/update-genotype-prod.sh master
running script as user hiseq.clinical, continue
on the host clinical-db.scilifelab.se, continue
This will install the latest version of genotype on master in production, are you sure? y/[n]y
remote: Enumerating objects: 158, done.
remote: Counting objects: 100% (158/158), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 293 (delta 133), reused 131 (delta 123), pack-reused 135
Receiving objects: 100% (293/293), 53.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (192/192), completed with 14 local objects.
From https://github.com/clinical-genomics/genotype
   7599ee7..3882cda  master     -> origin/master
 * [new branch]      CI/add-jobs -> origin/CI/add-jobs
 * [new branch]      new_lib_path -> origin/new_lib_path
 * [new branch]      trending_dev -> origin/trending_dev
 * [new tag]         2.3.3      -> 2.3.3
 * [new tag]         2.3.0      -> 2.3.0
 * [new tag]         2.3.1      -> 2.3.1
 * [new tag]         2.3.2      -> 2.3.2
Removing tests/store/test_store_trending.py
Removing genotype/store/trending.py
Merge made by the 'recursive' strategy.
 .bumpversion.cfg                   |   2 +-
 .github/CODEOWNERS                 |   5 +++++
 .github/PULL_REQUEST_TEMPLATE      |  25 +++++++++++++++++++++++++
 genotype/load/plate.py             |   2 +-
 genotype/server/admin.py           |   4 ++--
 genotype/store/api.py              |  32 ++++++++++++++++++++++++++++++--
 genotype/store/cli.py              |  92 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------
 genotype/store/export.py           |  93 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 genotype/store/trending.py         |  61 -------------------------------------------------------------
 requirements.txt                   |   6 ++++--
 setup.py                           |   5 +++--
 tests/store/test_store_export.py   | 166 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 tests/store/test_store_trending.py |  95 -----------------------------------------------------------------------------------------------
 13 files changed, 391 insertions(+), 197 deletions(-)
 create mode 100644 .github/CODEOWNERS
 create mode 100644 .github/PULL_REQUEST_TEMPLATE
 create mode 100644 genotype/store/export.py
 delete mode 100644 genotype/store/trending.py
 create mode 100644 tests/store/test_store_export.py
 delete mode 100644 tests/store/test_store_trending.py
Processing /home/hiseq.clinical/genotype
Collecting click (from genotype==2.3.3)
  Downloading https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 8.7MB/s
Requirement already up-to-date: PyYAML in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Requirement already up-to-date: Alchy in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Collecting SQLAlchemy (from genotype==2.3.3)
  Downloading https://files.pythonhosted.org/packages/8c/30/4134e726dd5ed13728ff814fa91fc01c447ad8700504653fe99d91fdd34b/SQLAlchemy-1.3.15.tar.gz (6.1MB)
    100% |████████████████████████████████| 6.1MB 174kB/s
Requirement already up-to-date: cyvcf2<0.10.0 in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Requirement already up-to-date: xlrd in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Requirement already up-to-date: pymysql in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Collecting pysam (from genotype==2.3.3)
  Downloading https://files.pythonhosted.org/packages/25/7e/098753acbdac54ace0c6dc1f8a74b54c8028ab73fb027f6a4215487d1fea/pysam-0.15.4.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 344kB/s
    Complete output from command python setup.py egg_info:
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: (sysconfig) CC=gcc -pthread
    # pysam: (sysconfig) CFLAGS=-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    # pysam: (sysconfig) LDFLAGS=-L/home/hiseq.clinical/miniconda/envs/prod170926/lib -Wl,-rpath=/home/hiseq.clinical/miniconda/envs/prod170926/lib,--no-as-needed
    checking for gcc... gcc -pthread
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc -pthread accepts -g... yes
    checking for gcc -pthread option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking for grep that handles long lines and -e... /bin/grep
    checking for C compiler warning flags... unknown
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... gcc -pthread -E
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for library containing recv... none required
    checking for bzlib.h... no
    checking for BZ2_bzBuffToBuffCompress in -lbz2... no
    configure: error: libbzip2 development files not found

    The CRAM format may use bzip2 compression, which is implemented in HTSlib
    by using compression routines from libbzip2 <http://www.bzip.org/>.

    Building HTSlib requires libbzip2 development files to be installed on the
    build machine; you may need to ensure a package such as libbz2-dev (on Debian
    or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    checking for gcc... gcc -pthread
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc -pthread accepts -g... yes
    checking for gcc -pthread option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking for grep that handles long lines and -e... /bin/grep
    checking for C compiler warning flags... unknown
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... gcc -pthread -E
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for library containing recv... none required
    checking for bzlib.h... no
    checking for BZ2_bzBuffToBuffCompress in -lbz2... no
    configure: error: libbzip2 development files not found

    The CRAM format may use bzip2 compression, which is implemented in HTSlib
    by using compression routines from libbzip2 <http://www.bzip.org/>.

    Building HTSlib requires libbzip2 development files to be installed on the
    build machine; you may need to ensure a package such as libbz2-dev (on Debian
    or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    config.mk:2: *** Resolve configure error first.  Stop.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ue_161q3/pysam/setup.py", line 241, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-build-ue_161q3/pysam/setup.py", line 68, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ue_161q3/pysam/
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(prod170926) [hiseq.clinical@hippocampus clinical-db.scilifelab.se]$ genotype --version
genotype, version 2.2.5
(prod170926) [hiseq.clinical@hippocampus clinical-db.scilifelab.se]$ bash ~/STAGE/servers/resources/clinical-db.scilifelab.se/update-genotype-prod.sh master
running script as user hiseq.clinical, continue
on the host clinical-db.scilifelab.se, continue
This will install the latest version of genotype on master in production, are you sure? y/[n]y
Already up-to-date.
Processing /home/hiseq.clinical/genotype
Collecting click (from genotype==2.3.3)
  Using cached https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl
Requirement already up-to-date: PyYAML in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Requirement already up-to-date: Alchy in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Collecting SQLAlchemy (from genotype==2.3.3)
  Using cached https://files.pythonhosted.org/packages/8c/30/4134e726dd5ed13728ff814fa91fc01c447ad8700504653fe99d91fdd34b/SQLAlchemy-1.3.15.tar.gz
Requirement already up-to-date: cyvcf2<0.10.0 in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Requirement already up-to-date: xlrd in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Requirement already up-to-date: pymysql in /home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages (from genotype==2.3.3)
Collecting pysam (from genotype==2.3.3)
  Using cached https://files.pythonhosted.org/packages/25/7e/098753acbdac54ace0c6dc1f8a74b54c8028ab73fb027f6a4215487d1fea/pysam-0.15.4.tar.gz
    Complete output from command python setup.py egg_info:
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: (sysconfig) CC=gcc -pthread
    # pysam: (sysconfig) CFLAGS=-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    # pysam: (sysconfig) LDFLAGS=-L/home/hiseq.clinical/miniconda/envs/prod170926/lib -Wl,-rpath=/home/hiseq.clinical/miniconda/envs/prod170926/lib,--no-as-needed
    checking for gcc... gcc -pthread
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc -pthread accepts -g... yes
    checking for gcc -pthread option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking for grep that handles long lines and -e... /bin/grep
    checking for C compiler warning flags... unknown
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... gcc -pthread -E
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for library containing recv... none required
    checking for bzlib.h... no
    checking for BZ2_bzBuffToBuffCompress in -lbz2... no
    configure: error: libbzip2 development files not found

    The CRAM format may use bzip2 compression, which is implemented in HTSlib
    by using compression routines from libbzip2 <http://www.bzip.org/>.

    Building HTSlib requires libbzip2 development files to be installed on the
    build machine; you may need to ensure a package such as libbz2-dev (on Debian
    or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    checking for gcc... gcc -pthread
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc -pthread accepts -g... yes
    checking for gcc -pthread option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking for grep that handles long lines and -e... /bin/grep
    checking for C compiler warning flags... unknown
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... gcc -pthread -E
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for library containing recv... none required
    checking for bzlib.h... no
    checking for BZ2_bzBuffToBuffCompress in -lbz2... no
    configure: error: libbzip2 development files not found

    The CRAM format may use bzip2 compression, which is implemented in HTSlib
    by using compression routines from libbzip2 <http://www.bzip.org/>.

    Building HTSlib requires libbzip2 development files to be installed on the
    build machine; you may need to ensure a package such as libbz2-dev (on Debian
    or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    config.mk:2: *** Resolve configure error first.  Stop.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-liqz_hhh/pysam/setup.py", line 241, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-build-liqz_hhh/pysam/setup.py", line 68, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-liqz_hhh/pysam/
```

**Comment by henrikstranneheim** [comment]
@patrikgrenfeldt Done right? I am closing this one. Reopen if you disagree
